Title: gnome-settings-daemon Update
Packages: 
    - gnome-settings-daemon
Release: MeeGo 1.2.0
Repository: MeeGo_1.2.0
Project: MeeGo:1.2.0:oss
Bugs:
    - 3496
Description: |
    * Fixed clone mode showed with external monitor connected after boot issue
Type: recommended
Status: testing
ID: gnome-settings-daemon
   
