Title: image-configurations Update
Packages:
    - image-configurations
Release: MeeGo 1.2.0
Repository: MeeGo_1.2.0
Project: MeeGo:1.2.0:oss
Bugs:
    - 17502
Description: |
    * Need this for the Upate release images
    * Image configuration changes for IVI XFCE support. BMC#17502
Type: recommended
Status: testing
ID: image-configurations
