Title: meego-ivi-configs Update
Packages: 
    - meego-ivi-configs
Release: MeeGo 1.2.0
Repository: MeeGo_1.2.0
Project: MeeGo:1.2.0:oss
Bugs:
    - 19052
    - 17393
Description: |
    * added gconf key for setting screensaver timeout to 0, keep it from bringing up lockscreen after 180 secs  
    * added xorg config setting for disabling dpms from triggering screensaver after 10 mins 
Type: recommended
Status: testing
ID: meego-ivi-configs
