Title: meego-netbook-settings Update
Packages: 
    - meego-netbook-settings
Release: MeeGo 1.2.0
Repository: MeeGo_1.2.0
Project: MeeGo:1.2.0:oss
Bugs:
    - 22884
Description: |
    * Prevent chromium to ask for default browser setting (BMC#22884)
Type: recommended
Status: testing
ID: meego-netbook-settings
