Title: system-config-printer Update
Packages: 
    - system-config-printer
Release: MeeGo 1.2.0
Repository: MeeGo_1.2.0
Project: MeeGo:1.2.0:oss
Bugs:
    - 19132
Description: |
    * Fixed Printer setting and email setting will go to another zone issue
Type: recommended
Status: testing
ID: system-config-printer
