Title: system-config-language Update
Packages: 
    - system-config-language
Release: MeeGo 1.2.0
Repository: MeeGo_1.2.0
Project: MeeGo:1.2.0:oss
Bugs:
    - 291
Description: |
    * Fixed time zone cannot be selected issue 
Type: recommended
Status: testing
ID: system-config-language
